/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studymanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saifu
 */
public class ExamRoutine extends javax.swing.JFrame {

    /**
     * Creates new form ExamRoutine
     */
    public ExamRoutine() {
        initComponents();
        table_update();
    }
    Connection con1;
    PreparedStatement insert;
    private void table_update(){
        int c;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/coursemanagement","root",""); //set connection with database
            insert = con1.prepareStatement("select * from examroutine");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
            Df.setRowCount(0);
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int a =1 ;a<=c; a++){
                    v2.add(rs.getInt("exam_no"));
                    v2.add(rs.getDate("Exam_Date"));
                    v2.add(rs.getString("Exam_Time"));
                    v2.add(rs.getString("Exam_Subject"));
                    
                }
                Df.addRow(v2); 
            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CourseTask.class.getName()).log(Level.SEVERE, null, ex);
           
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TaskDeletejButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HomejButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        examjDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        ExamTimejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ExamSubjectjTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ExamRoutineAddjButton = new javax.swing.JButton();
        TaskUpdatejButton = new javax.swing.JButton();
        TaskclearjButton = new javax.swing.JButton();
        TaskDeletejButton1 = new javax.swing.JButton();

        TaskDeletejButton.setBackground(new java.awt.Color(255, 0, 0));
        TaskDeletejButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TaskDeletejButton.setText("Delete");
        TaskDeletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDeletejButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Routine");

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Exam Routine");

        HomejButton.setBackground(new java.awt.Color(51, 51, 255));
        HomejButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HomejButton.setText("Home");
        HomejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomejButton)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(HomejButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Exam Date :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Exam Time :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Exam Subject :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam No.", "Date  (YYY-MM-DD)", "Time", "Subject"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        ExamRoutineAddjButton.setBackground(new java.awt.Color(51, 255, 0));
        ExamRoutineAddjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ExamRoutineAddjButton.setText("Add");
        ExamRoutineAddjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamRoutineAddjButtonActionPerformed(evt);
            }
        });

        TaskUpdatejButton.setBackground(new java.awt.Color(255, 255, 0));
        TaskUpdatejButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TaskUpdatejButton.setText("Update");
        TaskUpdatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskUpdatejButtonActionPerformed(evt);
            }
        });

        TaskclearjButton.setBackground(new java.awt.Color(51, 51, 255));
        TaskclearjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TaskclearjButton.setText("Clear");
        TaskclearjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskclearjButtonActionPerformed(evt);
            }
        });

        TaskDeletejButton1.setBackground(new java.awt.Color(255, 0, 0));
        TaskDeletejButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TaskDeletejButton1.setText("Delete");
        TaskDeletejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDeletejButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(ExamRoutineAddjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExamSubjectjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(examjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TaskclearjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(TaskDeletejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(ExamTimejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(TaskUpdatejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(examjDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ExamTimejTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExamSubjectjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExamRoutineAddjButton)
                    .addComponent(TaskUpdatejButton)
                    .addComponent(TaskclearjButton)
                    .addComponent(TaskDeletejButton1))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExamRoutineAddjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamRoutineAddjButtonActionPerformed
        // TODO add your handling code here:
        java.sql.Date examdate = new java.sql.Date(examjDateChooser.getDate().getTime()); //get input from datechooser1
        String examtime = ExamTimejTextField.getText();  //get input from text field1
        String examsubject = ExamSubjectjTextField.getText();  //get input from text field2

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/coursemanagement","root",""); //set connection with database
            insert = con1.prepareStatement("insert into examroutine(Exam_Date,Exam_Time,Exam_Subject)values(?,?,?)");
            insert.setDate(1,examdate);
            insert.setString(2,examtime);
            insert.setString(3,examsubject);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            table_update();

            examjDateChooser.setDate(null);
            ExamTimejTextField.setText("");
            ExamSubjectjTextField.setText("");
            ExamTimejTextField.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CourseTask.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to Add Record");

        }

    }//GEN-LAST:event_ExamRoutineAddjButtonActionPerformed

    private void TaskUpdatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskUpdatejButtonActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        try {
            
            int examno = Integer.parseInt(Df.getValueAt(selectedIndex,0).toString());
            
            java.sql.Date examdate = new java.sql.Date(examjDateChooser.getDate().getTime()); //get input from datechooser1
            String examtime = ExamTimejTextField.getText();  //get input from text field1
            String examname = ExamSubjectjTextField.getText();  //get input from text field2
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/coursemanagement", "root", ""); //set connection with database
            insert = con1.prepareStatement("update examroutine set Exam_Date=?,Exam_Time=?,Exam_Subject=? where exam_no=?");
            insert.setDate(1, examdate);
            insert.setString(2, examtime);
            insert.setString(3, examname);
            insert.setInt(4,examno);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");
            table_update();

            examjDateChooser.setDate(null);
            ExamTimejTextField.setText("");
            ExamSubjectjTextField.setText("");
            ExamTimejTextField.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CourseTask.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to Add Record");

        }
    }//GEN-LAST:event_TaskUpdatejButtonActionPerformed

    private void TaskclearjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskclearjButtonActionPerformed
        // TODO add your handling code here:
        examjDateChooser.setDate(null);
        ExamTimejTextField.setText("");
        ExamSubjectjTextField.setText("");
        ExamTimejTextField.requestFocus();
    }//GEN-LAST:event_TaskclearjButtonActionPerformed

    private void TaskDeletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDeletejButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskDeletejButtonActionPerformed

    private void TaskDeletejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDeletejButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        try {
            
            int examno = Integer.parseInt(Df.getValueAt(selectedIndex,0).toString());
            
            int dialogresult = JOptionPane.showConfirmDialog(null,"Do you want to delete this record?","Warning",JOptionPane.YES_NO_OPTION);
            
            if(dialogresult==JOptionPane.YES_OPTION){
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/coursemanagement", "root", ""); //set connection with database
            insert = con1.prepareStatement("delete from examroutine where exam_no =?");
            insert.setInt(1,examno);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Deleted");
            table_update();

            examjDateChooser.setDate(null);
            ExamTimejTextField.setText("");
            ExamSubjectjTextField.setText("");
            ExamTimejTextField.requestFocus();
            
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CourseTask.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to Add Record");

        }
        
    }//GEN-LAST:event_TaskDeletejButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        java.util.Date date = (java.util.Date) Df.getValueAt(selectedIndex, 1);
        examjDateChooser.setDate(date);
        ExamTimejTextField.setText(Df.getValueAt(selectedIndex,2).toString());
        ExamSubjectjTextField.setText(Df.getValueAt(selectedIndex,3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void HomejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomejButtonActionPerformed
        // TODO add your handling code here:
        homePage home = new homePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomejButtonActionPerformed


    public  void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamRoutine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamRoutine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamRoutine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamRoutine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ExamRoutine().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExamRoutineAddjButton;
    private javax.swing.JTextField ExamSubjectjTextField;
    private javax.swing.JTextField ExamTimejTextField;
    private javax.swing.JButton HomejButton;
    private javax.swing.JButton TaskDeletejButton;
    private javax.swing.JButton TaskDeletejButton1;
    private javax.swing.JButton TaskUpdatejButton;
    private javax.swing.JButton TaskclearjButton;
    private com.toedter.calendar.JDateChooser examjDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
